config/routes.rb
Books::Application.routes.draw do
  root :to => 'authors#index'
    resources :authors, :books

end

app/models/author.rb
# == Schema Information
#
# Table name: authors
#
#  id         :integer          not null, primary key
#  name       :text
#  bio        :text
#  genre      :text
#  image      :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Author < ActiveRecord::Base
  attr_accessible :name, :bio, :genre, :image
  has_many :books
end

app/models/book.rb
# == Schema Information
#
# Table name: books
#
#  id          :integer          not null, primary key
#  title       :text
#  description :text
#  isbn        :text
#  image       :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  author_id   :integer
#

class Book < ActiveRecord::Base
attr_accessible :title, :description, :isbn, :image, :author_id
belongs_to :author
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  def index
    @authors = Author.all
  end

  def new
    @author = Author.new
  end

  def create
    author = Author.create(params[:author])
    redirect_to(author)
  end

  def show
    @author = Author.find(params[:id])

 end

  def edit
    @author = Author.find(params[:id])
  end

  def update
    author = Author.find(params[:id])
    author.update_attributes(params[:author])
    redirect_to(author)
  end

  def destroy
    author = Author.find(params[:id])
    author.destroy
    redirect_to(authors_path)
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all
  end

  def new
    @book = Book.new
  end

  def create
    book = Book.create(params[:book])
    redirect_to(book)
  end


  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to(books_path)
  end

  def show
    @book = Book.find(params[:id])
  end


  def edit
    @book = Book.find(params[:id])
  end

  def update
    book = Book.find(params[:id])
    book.update_attributes(params[:book])
    redirect_to(books_path)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/authors/_form.html.erb
<%= form_for @author do |f| %>

  <%= f.label :name %><br/>
  <%= f.text_area :name %><br/>
  <%= f.label :bio %><br/>
  <%= f.text_area :bio %> <br/>
   <%= f.label :genre %><br/>
  <%= f.text_area :genre %> <br/>
  <%= f.label :image %><br/>
  <%= f.text_area :image %> <br/>

  <%= f.submit %>
  <% end %>

app/views/authors/edit.html.erb
<h1>edit author<h1>
  <%= render :partial => 'form' %>

app/views/authors/index.html.erb
<% @authors.each do |author| %>

<ul>
  <li><%= image_tag(author.image) %></li>
  <li><%= link_to(author.name, author) %></li>
  <li><%= author.bio %> </li>
  <li><%= author.genre %> </li>
</ul>

<% end %>

app/views/authors/new.html.erb
<h1> New Author</h1>
  <%= render :partial => 'form' %>

app/views/authors/show.html.erb
<% @authors.each do |author| %>
  <%= image_tag(author.image) %><br/>
  <%= author.name %><br/>
  <%= author.bio %><br/>
  <%= author.genre %><br/>


<% end %>

    <%= link_to 'edit', edit_author_path(@author) %>
    <%= link_to 'delete', @author, :method => :delete %>

<hr>

<% @author.books.each do |book| %>

  <%= book.title %><br/>
  <%= book.description %><br/>
  <%= book.isbn %><br/>
  <%= book.image %><br/>

<% end %>

app/views/books/_form.html.erb
<%= form_for @book do |f| %>

  <%= f.label :title %><br/>
  <%= f.text_area :title %><br/>
  <%= f.label :description %><br/>
  <%= f.text_area :description %> <br/>
   <%= f.label :isbn %><br/>
  <%= f.text_area :isbn %> <br/>
  <%= f.label :image %><br/>
  <%= f.text_area :image %> <br/>

  <%= f.label :author_id %>
  <%= f.select :author_id, Author.all.map {|author| [author.name, author.id]},
   :include_blank => true, :prompt => 'select author' %><br/>

  <%= f.submit %>
  <% end %>

app/views/books/edit.html.erb
<h1>edit book<h1>
  <%= render :partial => 'form' %>

app/views/books/index.html.erb
<% @books.each do |book| %>
<ul>
<%= image_tag(book.image) %></li>
  <li><%= link_to(book.title, book) %></li>
<li><%= book.description %> </li>
  <li><%= book.isbn %> </li>
</ul>

<% end %>

app/views/books/new.html.erb
<h1> New Book</h1>
  <%= render :partial => 'form' %>

app/views/books/show.html.erb
<%= @book %>
<%= link_to 'edit', edit_book_path(@book) %>
<%= link_to 'delete', @book, :method => :delete %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Books</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav>
  <ul>
    <li><%= link_to('new author', new_author_path) %></li>
    <li><%= link_to('new book', new_book_path) %></li>
  </ul>
</nav>




<%= yield %>

</body>
</html>